# Generated by Django 2.2.5 on 2020-04-03 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200305_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=500)),
                ('product_main_img', models.CharField(max_length=200)),
                ('product_slide_img', models.CharField(max_length=1000)),
                ('product_detail', models.CharField(max_length=3000)),
                ('product_sku', models.CharField(max_length=1000)),
                ('product_price', models.FloatField()),
                ('product_stock', models.IntegerField()),
                ('product_ordernum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttrKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr_name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product_Category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_price', models.FloatField()),
                ('product_stock', models.IntegerField()),
                ('product_sku', models.CharField(max_length=1000)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttrValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr_value_name', models.CharField(max_length=50)),
                ('attr_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductAttrKey')),
            ],
        ),
    ]
